version: '3'

services:

  storage:
      image: carcassmysql_storage
      expose:
        - "3306"    
      ports:
        - "3306:3306"
      networks:
        - netmain
      volumes:
        - var_lib_mysql:/var/lib/mysql
        - etc_mysql:/etc/mysql
        - var_log_mysql:/var/log/mysql     

  mediatry:
      image: carcassmysql_mediatry
      tty: true
      networks:
        - netmain
      depends_on:
        - storage
      environment:
        - PROJECT=mediatry      
        - WORKON_HOME=/mediatry/.env         
        - DJANGO_SETTINGS_MODULE=settings.dev        
      volumes:
        - ../../images/mediatry/src:/mediatry
      # .............................................        
      command: /usr/local/bin/migrate.sh

volumes:
  var_lib_mysql:
  etc_mysql:
  var_log_mysql:              

networks:
  netmain:
    driver: bridge  